services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - rabbitmq
    environment:
      - CONFIG_PATH=/app/config.yaml
    volumes:
      - ./config:/app/config
    networks:
      - tenant-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tenantdb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - tenant-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - tenant-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  tenant-network:

volumes:
  db-data:
