// Code generated by mockery v2.46.0. DO NOT EDIT.

package mockrepository

import (
	context "context"
	model "tenant/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// TenantRepository is an autogenerated mock type for the TenantRepository type
type TenantRepository struct {
	mock.Mock
}

// CreateTenant provides a mock function with given fields: ctx, tenant
func (_m *TenantRepository) CreateTenant(ctx context.Context, tenant *model.Tenant) error {
	ret := _m.Called(ctx, tenant)

	if len(ret) == 0 {
		panic("no return value specified for CreateTenant")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Tenant) error); ok {
		r0 = rf(ctx, tenant)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetTenantByClientID provides a mock function with given fields: ctx, clientID
func (_m *TenantRepository) GetTenantByClientID(ctx context.Context, clientID string) (*model.Tenant, error) {
	ret := _m.Called(ctx, clientID)

	if len(ret) == 0 {
		panic("no return value specified for GetTenantByClientID")
	}

	var r0 *model.Tenant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Tenant, error)); ok {
		return rf(ctx, clientID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Tenant); ok {
		r0 = rf(ctx, clientID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Tenant)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, clientID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SoftDeleteTenant provides a mock function with given fields: ctx, clientID
func (_m *TenantRepository) SoftDeleteTenant(ctx context.Context, clientID string) error {
	ret := _m.Called(ctx, clientID)

	if len(ret) == 0 {
		panic("no return value specified for SoftDeleteTenant")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, clientID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTenantRepository creates a new instance of TenantRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTenantRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TenantRepository {
	mock := &TenantRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
